# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /workspace

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the typescript source code
RUN npm run build

EXPOSE 3000

CMD ["node", "build/index.js"]
